<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>beluga_ros2</name>
  <version>1.0.0</version>
  <description>ROS2 launch for Beluga Localization</description>

  <maintainer email="teresa.ortega@gethen.io">Maria Teresa Ortega</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>beluga_amcl</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
